/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DecisionsSlugRouteImport } from './routes/decisions/$slug'
import { Route as FailuresSlugRouteImport } from './routes/failures/$slug'
import { Route as LessonsIdRouteImport } from './routes/lessons/$id'
import { Route as PeopleSlugRouteImport } from './routes/people/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsSlugRoute = DecisionsSlugRouteImport.update({
  id: '/decisions/$slug',
  path: '/decisions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresSlugRoute = FailuresSlugRouteImport.update({
  id: '/failures/$slug',
  path: '/failures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/decisions/$slug': typeof DecisionsSlugRoute
  '/failures/$slug': typeof FailuresSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/people/$slug': typeof PeopleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/decisions/$slug': typeof DecisionsSlugRoute
  '/failures/$slug': typeof FailuresSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/people/$slug': typeof PeopleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/decisions/$slug': typeof DecisionsSlugRoute
  '/failures/$slug': typeof FailuresSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/people/$slug': typeof PeopleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/decisions/$slug'
    | '/failures/$slug'
    | '/lessons/$id'
    | '/people/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/decisions/$slug'
    | '/failures/$slug'
    | '/lessons/$id'
    | '/people/$slug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/decisions/$slug'
    | '/failures/$slug'
    | '/lessons/$id'
    | '/people/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DecisionsSlugRoute: typeof DecisionsSlugRoute
  FailuresSlugRoute: typeof FailuresSlugRoute
  LessonsIdRoute: typeof LessonsIdRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$slug': {
      id: '/decisions/$slug'
      path: '/decisions/$slug'
      fullPath: '/decisions/$slug'
      preLoaderRoute: typeof DecisionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures/$slug': {
      id: '/failures/$slug'
      path: '/failures/$slug'
      fullPath: '/failures/$slug'
      preLoaderRoute: typeof FailuresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DecisionsSlugRoute: DecisionsSlugRoute,
  FailuresSlugRoute: FailuresSlugRoute,
  LessonsIdRoute: LessonsIdRoute,
  PeopleSlugRoute: PeopleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
